# Generated by Django 3.1.3 on 2020-11-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racs', '0003_otdel'),
        ('accounts', '0002_auto_20201128_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otdel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='racs.otdel'),
            preserve_default=False,
        ),
    ]
