# Generated by Django 3.1.3 on 2020-11-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summ', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EX', 'Экспертиза'), ('DO', 'Доработка'), ('PR', 'Признано'), ('OT', 'Отклонено'), ('IP', 'Идёт опытное применение'), ('ON', 'Опытное применение завершено неуспешно'), ('OU', 'Опытное применение завершено успешно'), ('TU', 'Тиражирование завершено успешно'), ('TN', 'Тиражирование завершено неуспешно')], max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('curr_desc', models.TextField()),
                ('new_desc', models.TextField()),
                ('pos_effect', models.TextField()),
                ('costs', models.ManyToManyField(related_name='claims', to='racs.Cost')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eclaims', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ManyToManyField(related_name='claims', to='racs.Term')),
                ('users', models.ManyToManyField(related_name='uclaims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
