# Generated by Django 3.1.3 on 2020-11-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racs', '0003_otdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='costs',
            field=models.ManyToManyField(blank=True, related_name='claims', to='racs.Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('EX', 'Экспертиза'), ('DO', 'Доработка'), ('PR', 'Признано'), ('OT', 'Отклонено'), ('IP', 'Идёт опытное применение'), ('ON', 'Опытное применение завершено неуспешно'), ('OU', 'Опытное применение завершено успешно'), ('TU', 'Тиражирование завершено успешно'), ('TN', 'Тиражирование завершено неуспешно')], default='EX', max_length=15),
        ),
        migrations.AlterField(
            model_name='claim',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='claims', to='racs.Term'),
        ),
    ]
