# Generated by Django 3.1.3 on 2020-11-28 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('racs', '0004_auto_20201128_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='creation_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='users',
            field=models.ManyToManyField(related_name='uclaims', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
