# Generated by Django 3.1.3 on 2020-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racs', '0005_auto_20201128_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='category',
        ),
        migrations.AddField(
            model_name='claim',
            name='category',
            field=models.ManyToManyField(related_name='claims', to='racs.Category'),
        ),
    ]
