# Generated by Django 3.1.3 on 2020-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racs', '0006_auto_20201129_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='similars',
            field=models.ManyToManyField(blank=True, to='racs.Claim'),
        ),
    ]
